server:
  port: 9001

# Spring相关配置
spring:
  redis:
    # Redis服务器地址
    host: localhost
    # password:
    # Redis服务器连接端口
    port: 6379
    # 连接超时时间（记得添加单位，Duration）
    timeout: 100000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 0
    # 自定义属性：开启自定义前缀
    allow-prefix: true
    # 自定义属性：key的前缀，默认在注解@Cacheable、@CachePut等生效。
    prefix: "com:cxhit:study:"
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0